# Generated by Django 5.2 on 2025-05-07 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saladecine',
            name='capacidad',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='saladecine',
            name='tipoDeSala',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX'), ('4DX', '4DX')], default='2D', max_length=50),
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_termino', models.DateTimeField(editable=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.peliculas')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cine.saladecine')),
            ],
            options={
                'unique_together': {('sala', 'fecha_hora_inicio')},
            },
        ),
    ]
