# Generated by Django 5.2 on 2025-05-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mecanico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='descripction',
            new_name='description',
        ),
    ]
